stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master@classes/hotel-web
  tags:
    - web
  script:
    - docker build -t michaelpalmer/dockers:hotel .
    - docker push michaelpalmer/dockers:hotel
    - rancher-compose up -d -p --upgrade hotel-web
