stages:
  - deploy

deploy:
  stage: deploy
#  only:
#    - master@classes/hotel-web
  tags:
    - web
  script:
    - docker build -t michaelpalmer/hotel .
    - if [ ! -z "$(docker ps | grep hotel)" ]; then docker stop hotel; fi
    - if [ ! -z "$(docker ps -a | grep hotel)" ]; then docker rm -f hotel; fi
    - docker run -d -e VIRTUAL_HOST=hotel.michaeldpalmer.com --name hotel --restart always michaelpalmer/hotel