hotel-web:
  environment:
    VIRTUAL_HOST: hotel.michaeldpalmer.com
  external_links:
  - Database/mysql:mysql
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: host=aws
  tty: true
  log_opt: {}
  image: michaelpalmer/dockers:hotel
  stdin_open: true
